### ISSUE TITLE
Remove `pigments_from_rss` directory

### ISSUE THREAD

**Issue by cisaacstern** [alisonpchase/pigments-from-rrs#10]
Somehow, the `pigments_from_rss` (note the typo, __*rss*__) directory still exists in the `main` branch. 

We've already replicated all of the content within it into the correctly spelled package directory, so we should make a PR to remove it.

**Comment by alisonpchase** [comment]
Sounds good to me. In this case, would I delete it first and then make a PR with that change? Or does creating the PR step come first?

**Comment by cisaacstern** [comment]
1. In your local repo, first `git fetch origin` and `git merge origin/main` to ensure your local repo is synced with the `main` branch on GitHub.

> This ☝️ assumes your local repo is configured with `origin` as the name of the remote GitHub repo. To verify that, run `git remote -v`, which should output
> ```
> origin	https://github.com/alisonpchase/pigments-from-rrs.git (fetch)
> origin	https://github.com/alisonpchase/pigments-from-rrs.git (push)
> ```
> If the name to the left of the url is something other than `origin`, then swap that name into the commands above.
 
2. Make a new local branch with `git checkout -b rm-typo-dir` (or any name you choose instead of `rm-typo-dir`)
3. Delete the typo directory (e.g., `rm -r pigments_from_rss`)
4. Add and commit the changes (`git add -A`, `git commit -m 'deleted typo directory'`)
5. Push the changes to a new branch on GitHub (`git push origin rm-typo-dir`)
6. On https://github.com/alisonpchase/pigments-from-rrs, there should now be a prompt to open a PR from the new branch `rm-typo-dir`. Open the PR.
7. In the PR comment area, write "`Closes #10`". This will [automatically close this Issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) (Issue No. 10) when you merge the PR.
8. Merge the PR 🎉
